---
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/axia80_m20/wrench"
  gz_topic_name: "/axia80_m20/wrench"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/wrist_camera_1/image"
  gz_topic_name: "/wrist_camera_1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/wrist_camera_2/image"
  gz_topic_name: "/wrist_camera_2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/wrist_camera_3/image"
  gz_topic_name: "/wrist_camera_3/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/wrist_camera_1/camera_info"
  gz_topic_name: "/wrist_camera_1/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/wrist_camera_2/camera_info"
  gz_topic_name: "/wrist_camera_2/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/wrist_camera_3/camera_info"
  gz_topic_name: "/wrist_camera_3/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: true
