#!/bin/bash
# One-time setup for run_parallel.sh / run_parallel_multi.sh on Lambda.
#
# Creates N persistent distrobox-managed containers (aic_worker_0 .. aic_worker_{N-1})
# from ghcr.io/shu4dev/aic-eval:v1. Distrobox's --nvidia flag bind-mounts the
# host's libnvidia-gl-580-server libraries into the container, which is what
# Ogre2 / gz-rendering-ogre2 needs to find the OpenGL 3+ RenderSystem. Plain
# `docker run --gpus all` does NOT do those bind-mounts comprehensively — the
# symptom is `unable to find OpenGL 3+ Rendering Subsystem` followed by
# component_container exit -11. See docs/lambda_headless_setup.md for the
# original 3-terminal manual flow this matches.
#
# Each worker also gets a per-worker /entrypoint.sh bind-mounted over the
# image's baked-in one. The only difference between workers is the Zenoh
# router listen port: worker i listens on 7447+i. This is what unlocks
# concurrent multi-worker collection — without it, all containers would fight
# for host port 7447 under distrobox's --network host default.
#
# This script is idempotent for container creation, BUT the per-worker
# entrypoint mount is fixed at distrobox-create time. If you already have
# aic_worker_0 from an earlier run without the entrypoint mount, recreate it:
#   sudo docker rm -f aic_worker_0
#   bash scripts/setup_workers.sh
# Re-running with the same NUM_WORKERS on an already-set-up host is otherwise
# a no-op.
#
# Prerequisites (done once per Lambda box — see docs/lambda_headless_setup.md):
#   - sudo apt install -y libnvidia-gl-580-server  (matching the kernel module)
#   - sudo apt install -y distrobox
#   - docker login ghcr.io  (to pull the private aic-eval image)
#
# Usage:
#   bash scripts/setup_workers.sh                  # creates aic_worker_0
#   NUM_WORKERS=4 bash scripts/setup_workers.sh    # creates aic_worker_0..3
#
# Environment overrides (all optional):
#   NUM_WORKERS      how many worker containers to create  (default: 1)
#   IMAGE            container image                       (default: ghcr.io/shu4dev/aic-eval:v1)
#   AIC_DATA_DIR     host mounted-FS to expose to workers  (default: /home/ubuntu/aic-data)
#   NAME_PREFIX      worker container name prefix          (default: aic_worker)

set -euo pipefail

NUM_WORKERS="${NUM_WORKERS:-1}"
IMAGE="${IMAGE:-ghcr.io/shu4dev/aic-eval:v1}"
AIC_DATA_DIR="${AIC_DATA_DIR:-/home/ubuntu/aic-data}"
NAME_PREFIX="${NAME_PREFIX:-aic_worker}"

if ! command -v distrobox >/dev/null 2>&1; then
    echo "error: distrobox not found on PATH — run 'sudo apt install -y distrobox' first" >&2
    exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
    echo "error: docker not found on PATH" >&2
    exit 1
fi

export DBX_CONTAINER_MANAGER=docker

# Pre-pull the image once so each distrobox create doesn't redo it.
if ! sudo docker image inspect "$IMAGE" >/dev/null 2>&1; then
    echo "Pulling $IMAGE ..."
    sudo docker pull "$IMAGE"
fi

# Make sure the mounted-FS dir exists so distrobox doesn't refuse the bind.
mkdir -p "$AIC_DATA_DIR"

# Per-worker /entrypoint.sh files live here on the host and get bind-mounted
# over the image's baked-in /entrypoint.sh so each worker's Zenoh router binds
# a distinct host port (7447 + i) under distrobox's --network host. Without
# this, every worker would try to bind 7447 and only the first one wins.
ENTRYPOINTS_DIR="${AIC_DATA_DIR}/worker_entrypoints"
mkdir -p "$ENTRYPOINTS_DIR"

# Writes a per-worker entrypoint script to $1 with the Zenoh listen port set
# to $2. This mirrors the heredoc'd /entrypoint.sh in docker/aic_eval/Dockerfile
# line-for-line; if the upstream Dockerfile changes, regenerate this template
# from docker/aic_eval/Dockerfile.
write_worker_entrypoint() {
    local out_path="$1"
    local port="$2"
    # Docker auto-creates the bind source as a *directory* if `docker start`
    # runs before the host file exists. Once that happens, subsequent
    # `cat > "$out_path"` here fails with "Is a directory". Wipe any leftover
    # so we always start from a clean slot — works whether it's a file or dir.
    rm -rf "$out_path"
    cat > "$out_path" <<EOF
#!/bin/bash
# Auto-generated by scripts/setup_workers.sh — do not edit by hand.
# Per-worker Zenoh listen port: ${port}  (default in image: 7447)
set -e

. /ws_aic/install/setup.bash
export RMW_IMPLEMENTATION=rmw_zenoh_cpp

should_enable_acl() {
  [[ "\$AIC_ENABLE_ACL" == "true" || "\$AIC_ENABLE_ACL" == "1" ]]
}

if should_enable_acl; then
  if [[ ! ( -n "\$AIC_EVAL_PASSWD" && -n "\$AIC_MODEL_PASSWD" ) ]]; then
    echo "AIC_EVAL_PASSWD, AIC_MODEL_PASSWD must be provided"
    exit 1
  fi
  echo "eval:\$AIC_EVAL_PASSWD" >> /credentials.txt
  echo "model:\$AIC_MODEL_PASSWD" >> /credentials.txt
fi

export ZENOH_ROUTER_CONFIG_URI=/aic_zenoh_config.json5

ZENOH_CONFIG_OVERRIDE='mode="router"'
ZENOH_CONFIG_OVERRIDE+=';listen/endpoints=["tcp/[::]:${port}"]'
ZENOH_CONFIG_OVERRIDE+=';connect/endpoints=[]'
ZENOH_CONFIG_OVERRIDE+=';routing/router/peers_failover_brokering=true'
ZENOH_CONFIG_OVERRIDE+=';transport/shared_memory/enabled=false'
if should_enable_acl; then
  ZENOH_CONFIG_OVERRIDE+=';transport/auth/usrpwd/user="eval"'
  ZENOH_CONFIG_OVERRIDE+=';transport/auth/usrpwd/password="'"\$AIC_EVAL_PASSWD"'"'
  ZENOH_CONFIG_OVERRIDE+=';transport/auth/usrpwd/dictionary_file="/credentials.txt"'
fi
export ZENOH_CONFIG_OVERRIDE
echo "ZENOH_CONFIG_OVERRIDE_ROUTER=\$ZENOH_CONFIG_OVERRIDE"
ros2 run rmw_zenoh_cpp rmw_zenohd &
ZENOH_ROUTER_PID=\$!

trap "kill -SIGINT -\$ZENOH_EVAL_ROUTER_PID -\$ZENOH_ROUTER_PID" EXIT

# Peer override: the base aic_zenoh_config.json5 hardcodes
# connect/endpoints=["tcp/localhost:7447"]. Without overriding it, every
# in-container peer in workers ≥1 would connect to worker 0's router and split
# the worker's aic_engine from its own host-side aic_model. Repointing
# connect/endpoints at this worker's router is sufficient: the router has
# connect/endpoints=[] and listens on a unique port, so cross-router bridges
# can't form. We deliberately do NOT disable gossip/multicast here — ROS 2
# service discovery under rmw_zenoh_cpp relies on intra-fabric gossip
# declarations, e.g. LoadComposableNodes loading gz_server into ros_gz_container.
ZENOH_CONFIG_OVERRIDE='connect/endpoints=["tcp/localhost:${port}"]'
ZENOH_CONFIG_OVERRIDE+=';transport/shared_memory/enabled=false'
if should_enable_acl; then
  ZENOH_CONFIG_OVERRIDE+=';transport/auth/usrpwd/user="eval"'
  ZENOH_CONFIG_OVERRIDE+=';transport/auth/usrpwd/password="'"\$AIC_EVAL_PASSWD"'"'
  ZENOH_CONFIG_OVERRIDE+=';transport/auth/usrpwd/dictionary_file="/credentials.txt"'
fi
export ZENOH_CONFIG_OVERRIDE
echo "ZENOH_CONFIG_OVERRIDE_PEER=\$ZENOH_CONFIG_OVERRIDE"
exec ros2 launch aic_bringup aic_gz_bringup.launch.py "\$@"
EOF
    chmod 755 "$out_path"
}

echo "=== Setting up $NUM_WORKERS distrobox worker container(s) ==="
echo "Image:        $IMAGE"
echo "Mount:        $AIC_DATA_DIR  (visible inside container at the same path)"
echo "Entrypoints:  $ENTRYPOINTS_DIR/entrypoint_<i>.sh  (mounted over /entrypoint.sh)"
echo "Name prefix:  $NAME_PREFIX"
echo "Zenoh ports:  worker i listens on host port $((7447))..$((7447 + NUM_WORKERS - 1))"
echo ""

for i in $(seq 0 $((NUM_WORKERS - 1))); do
    name="${NAME_PREFIX}_${i}"
    worker_port=$((7447 + i))
    entrypoint_path="${ENTRYPOINTS_DIR}/entrypoint_${i}.sh"

    # Always regenerate the per-worker entrypoint — cheap, and keeps it in sync
    # if the user's upstream image gets rebuilt with a new entrypoint template.
    write_worker_entrypoint "$entrypoint_path" "$worker_port"

    if sudo docker container inspect "$name" >/dev/null 2>&1; then
        echo "[$name] already exists (port ${worker_port}) — skipping create"
        continue
    fi

    echo "[$name] creating via distrobox --nvidia (Zenoh port ${worker_port}) ..."
    # --root      run with sudo / root-owned container
    # --nvidia    bind-mount host NVIDIA GL/EGL libs (the critical bit for Ogre2)
    # --no-entry  don't drop the user into a shell at the end
    # --additional-flags carries arbitrary `docker create` flags:
    #   * -v ${AIC_DATA_DIR}:${AIC_DATA_DIR}            — mounted FS, identity-pathed
    #   * -v ${entrypoint_path}:/entrypoint.sh:ro       — per-worker Zenoh port
    #   * -v /usr/share/glvnd/egl_vendor.d/10_nvidia.json:...:ro
    #     distrobox --nvidia bind-mounts the libEGL_nvidia.so / libGLX_nvidia.so
    #     into /usr/lib/x86_64-linux-gnu, but it does NOT mount the ICD config
    #     into /usr/share/glvnd/egl_vendor.d/. Without that JSON at the standard
    #     path, libglvnd only sees 50_mesa.json and falls back to llvmpipe even
    #     though the NVIDIA libs are present. Mount it ourselves so the default
    #     EGL lookup works without needing __EGL_VENDOR_LIBRARY_FILENAMES.
    distrobox create \
        --root \
        --nvidia \
        --no-entry \
        --name "$name" \
        --image "$IMAGE" \
        --additional-flags "-v ${AIC_DATA_DIR}:${AIC_DATA_DIR} -v ${entrypoint_path}:/entrypoint.sh:ro -v /usr/share/glvnd/egl_vendor.d/10_nvidia.json:/usr/share/glvnd/egl_vendor.d/10_nvidia.json:ro"

    # distrobox lazily starts containers on first `enter`. Pre-start now so the
    # first run of run_parallel.sh doesn't pay that cost.
    sudo docker start "$name" >/dev/null
done

echo ""
echo "=== Done ==="
echo "Containers:"
for i in $(seq 0 $((NUM_WORKERS - 1))); do
    name="${NAME_PREFIX}_${i}"
    state="$(sudo docker inspect -f '{{.State.Status}}' "$name" 2>/dev/null || echo missing)"
    echo "  $name  ($state)"
done

cat <<MSG

Next steps:
  - Verify NVIDIA EGL works inside one of them. Two things matter here:
    (1) __EGL_VENDOR_LIBRARY_FILENAMES pins libglvnd to NVIDIA's ICD; without
        it, libglvnd loads both NVIDIA and Mesa, and the platform that
        succeeds first wins.
    (2) Pass -B to eglinfo to skip the GBM/X11 platform probes and test the
        Surfaceless platform directly. On Lambda's open NVIDIA kernel module,
        libdrm doesn't expose a /dev/dri driver-name association
        (eglinfo prints "pci id … driver (null)"), so NVIDIA's GBM probe
        fails. That GBM failure is benign — Ogre2 / gz-rendering use
        Surfaceless / EGL_PLATFORM_DEVICE_EXT for headless, which works:
      sudo docker exec \\
          -e __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json \\
          ${NAME_PREFIX}_0 eglinfo -B 2>&1 | grep -iE 'vendor|renderer|nvidia' | head -5
    Expected output starts with "EGL vendor string: NVIDIA" and includes a line
    like "OpenGL core profile renderer: NVIDIA A100-SXM4-40GB/PCIe/SSE2".
    If you instead see "EGL vendor string: Mesa Project / kms_swrast" from
    bare \`eglinfo\` (no -B), that's the GBM-default red herring, not a real
    failure.

  - Run an eval worker (run_parallel.sh sets the EGL env automatically):
      bash scripts/run_parallel.sh                      # uses ${NAME_PREFIX}_0
  - Tear down (if you ever want to recreate):
      sudo docker rm -f ${NAME_PREFIX}_0
MSG
