[package.build.backend]
name = "pixi-build-ros"
version = "==0.3.3.20260113.c8b6a54"
channels = [
  "https://prefix.dev/pixi-build-backends",
  "robostack-kilted",
  "conda-forge",
]

[package.build.config]
extra-package-mappings = [{ "python3-hidapi" = { conda = ["hidapi"] } }]
